/* jshint unused:false */
var EVENTSDATA = [
  {
    name: 'Angular Trainig Day',
    date: '2015-10-29T10:00:00',
    city: 'Bangkok, Thailand',
    talkName: '',
    summary: 'Come together for a free Angular Trainig Day in Bangkok!',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'https://www.eventbrite.de/e/angular-training-day-bangkok-tickets-18617003960',
  },
  {
    name: 'CodeTalks 2015',
    date: '2015-09-30T09:30:00',
    city: 'Hamburg, Germany',
    websiteUrl: 'http://codetalks.de',
    videoUrl: '',
    slidesUrl: '',
    talkName: 'Dependency Injection for future generations',
    summary: 'Pascal will introduce you to the concepts of Dependency Injection and how it is implemented in Angular 2.'
  },
  {
    name: 'CodeTalks 2015',
    date: '2015-09-29T09:30:00',
    city: 'Hamburg, Germany',
    websiteUrl: 'http://codetalks.de',
    videoUrl: '',
    slidesUrl: '',
    talkName: 'Rust - Rethinking System Programming',
    summary: 'Learn how the Rust programming language will change the way we build system applications in Christoph\'s talk at CodeTalks!'
  },
  {
    name: 'Angular Master Class',
    date: '2015-09-14T09:30:00',
    city: 'Helsinki, Finland',
    websiteUrl: 'http://thoughtram.io/angular-master-class.html',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'We are very happy to run our Angular Master Class in Helsinki!'
  },
  {
    name: 'Angular Master Class',
    date: '2015-08-03T09:30:00',
    city: 'Hanover, Germany',
    websiteUrl: 'http://thoughtram.io/angular-master-class.html',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'Home run! Join our Angular Master Class in Hanover!'
  },
  {
    name: 'Angular Master Class',
    date: '2015-07-15T09:30:00',
    city: 'Amsterdam, Netherlands',
    websiteUrl: 'http://thoughtram.io/angular-master-class.html',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'Meet Christoph and Pascal in Amsterdam at the Angular Master Class!'
  },
  {
    name: 'Betahaus Education',
    date: '2015-07-17T09:00:00',
    city: 'Hamburg, Germany',
    talkName: 'Angular Training Day',
    summary: 'We will be part of the Betahaus Education Program in Hamburg and give a full day training on Angular!',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'http://www.meetup.com/ng-bkk/',
  },
  {
    name: 'JSConf Budapest',
    date: '2015-05-14T09:00:00',
    city: 'Budapest, Hungary',
    talkName: 'Dependency Injection for Future Generations',
    summary: 'In this talk Pascal will speak about what DI is, why it is useful and how it can be even easier to use with TypeScript Annotations.',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'http://jsconfbp.com/',
  },
  {
    name: 'Angular Meetup Bangkok',
    date: '2015-04-17T19:00:00',
    city: 'Bangkok, Thailand',
    talkName: 'The best Angular yet!',
    summary: 'Meet Christoph when he talks about the best Angular yet at the Angular meetup in Bangkok.',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'http://www.meetup.com/ng-bkk/',
  },
  {
    name: 'Angular Meetup Vienna',
    date: '2015-03-18T19:00:00',
    city: 'Vienna, Austria',
    talkName: 'The Best Angular Yet!',
    summary: 'Come and say hi at Vienna\'s Angular meetup!',
    slidesUrl: 'http://thoughtram.github.io/the-best-angular-yet',
    videoUrl: '',
    websiteUrl: 'http://www.meetup.com/AngularJS-Vienna/events/219775723/',
  },
  {
    name: 'ng-conf',
    date: '2015-03-05T09:00:00',
    city: 'Salt Lake City, Utah',
    talkName: 'Better i18n for your Angular apps',
    summary: 'Learn about the new i18n story that is coming to Angular and meet Pascal at ng-conf!',
    slidesUrl: 'http://pascalprecht.github.io/slides/better-i18n-for-your-angular-apps',
    videoUrl: '',
    websiteUrl: 'http://ng-conf.org',
  },
  {
    name: 'goto; Amsterdam',
    date: '2015-06-17T09:00:00',
    city: 'Amsterdam, Netherlands',
    talkName: 'Dependency Injection for future Generations',
    summary: 'Learn about the new Dependency Injection system in Angular 2.0 and meet Pascal in Amsterdam.',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'http://gotocon.com/amsterdam-2015/',
  },
  {
    name: 'HannoverJS',
    date: '2015-01-22T19:00:00',
    city: 'Hanover, Germany',
    talkName: 'Componentize all the things!',
    summary: 'Don\'t know what Web Components are? Pascal is going to tell you about it.',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'http://hannoverjs.de',
  },
  {
    name: 'Voxxed Days Ticino Workshop',
    date: '2015-04-18T09:00:00',
    city: 'Ticino, Switzerland',
    websiteUrl: 'https://voxxeddays.com/ticino15/vdt-workshops/#angularjs',
    videoUrl: '',
    slidesUrl: '',
    talkName: 'Angular Training Day',
    summary: 'Pascal is going to run a full Angular training day at Voxxed Days Ticino!'
  },
  {
    name: 'Voxxed Days Ticino',
    date: '2015-04-18T09:00:00',
    city: 'Ticino, Switzerland',
    websiteUrl: 'https://www.voxxed.com/days-ticino15/',
    videoUrl: '',
    slidesUrl: '',
    talkName: 'Fireside chats about Angular 2.0',
    summary: 'In this talk we want to take a seat, set up a very cozy virtual fireplace and have a relaxed chat about Angular 2.0.'
  },
  {
    name: 'Angular Master Class',
    date: '2015-03-16T09:30:00',
    city: 'Vienna, Austria',
    websiteUrl: 'http://thoughtram.io/angular-master-class.html',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'We are going to run our Angular Master Class in Vienna.'
  },
  {
    name: 'AngularJS Days',
    date: '2015-03-04T09:30:00',
    city: 'Munich, Germany',
    websiteUrl: 'http://angularjs-days.de/2015',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'Say hello in Munich to Christoph and Pascal while they are running two workshops on Angular directives.'
  },
  {
    name: 'NG-NL',
    date: '2015-02-13T09:00:00',
    city: 'Amsterdam, Netherlands',
    websiteUrl: 'http://ng-nl.org',
    videoUrl: '',
    slidesUrl: '',
    talkName: 'The best Angular yet!',
    summary: 'Meet Christoph and Pascal when they talk about the best Angular yet at Amsterdams own AngularJS conference.'
  },
  {
    name: 'Git Master Class',
    date: '2015-01-15T09:30:00',
    city: 'Amsterdam, Netherlands',
    websiteUrl: 'http://thoughtram.io/git-master-class.html',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'Meet Christoph and Pascal in Amsterdam at the Git Master Class!'
  },
  {
    name: 'ngEurope',
    date: '2014-10-22T08:30:00',
    city: 'Paris, France',
    talkName: '"Don\'t stop thinking about tomorrow!" - AngularJS and Web Components',
    summary: 'Learn how to integrate Web Components with the AngularJS of today in Pascals at ngEurope.',
    slidesUrl: 'http://pascalprecht.github.io/dont-stop-thinking-about-tomorrow',
    videoUrl: 'https://www.youtube.com/watch?v=gSTNTXtQwaY',
    websiteUrl: 'http://ngeurope.org',
  },
  {
    name: 'JsIst',
    date: '2014-09-27T08:30:00',
    city: 'Istanbul, Turkey',
    talkName: 'Disussion Panel',
    summary: 'Join Christoph at the discussion Panel and talk about the web.',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'http://jsist.org',
  },
  {
    name: 'JsIst',
    date: '2014-09-27T08:30:00',
    city: 'Istanbul, Turkey',
    talkName: 'Componentize all the things!',
    summary: 'Hello Istanbul! Pascal talks about Web Components and Polymer.',
    slidesUrl: 'http://pascalprecht.github.io/slides/componentize-all-the-things/#/',
    videoUrl: '',
    websiteUrl: 'http://jsist.org',
  },
  {
    name: 'IstanbulJS',
    date: '2014-09-26T18:30:00',
    city: 'Istanbul, Turkey',
    talkName: 'nickel.rs - Web Application Framework for Rust',
    summary: 'Christoph talks about web application development in Rust',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'https://twitter.com/jstanbulorg',
  },
  {
    name: 'Git Training Day',
    date: '2014-09-20T08:30:00',
    city: 'Istanbul, Turkey',
    talkName: '',
    summary: 'Christoph and Pascal are running a free Git Training Day in Istanbul.',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: '',
  },
  {
    name: 'EnterJS',
    date: '2014-07-01T08:30:00',
    city: 'Cologne, Germany',
    talkName: 'E2E Testing with Protractor',
    summary: 'Pascal is going to talk about E2E testing with the Protractor framework.',
    slidesUrl: 'http://pascalprecht.github.io/slides/e2e-testing-with-protractor',
    videoUrl: '',
    websiteUrl: 'http://enterjs.de/',
  },
  {
    name: 'Codefront.io',
    date: '2014-05-01T08:30:00',
    city: 'Linz, Austria',
    talkName: 'Full Spectrum Testing',
    summary: 'Meet Carmen and Pascal and talk about all things testing!',
    slidesUrl: 'http://pascalprecht.github.io/full-spectrum-testing-slides',
    videoUrl: '',
    websiteUrl: 'http://codefront.io/',
  },
  {
    name: 'JSUnconf',
    date: '2014-04-26T09:00:00',
    city: 'Hamburg, Germany',
    talkName: 'The Secrets of the Git Ninjas',
    summary: 'Christoph on the secrets of Git Ninjas.',
    slidesUrl: 'http://slides.com/cburgdorf/the-secrets-of-the-git-ninjas/#/',
    videoUrl: '',
    websiteUrl: 'http://2014.jsunconf.eu/',
  },
  {
    name: 'Berlin AngularJS Meetup',
    date: '2014-03-12T19:00:00',
    city: 'Berlin, Germany',
    talkName: 'i18n with angular-translate',
    summary: 'Pascal is going to talk about angular-translate and AngularJS. Come and say hi!',
    slidesUrl: 'http://pascalprecht.github.io/slides/i18n-with-angular-translate-2/#/',
    videoUrl: '',
    websiteUrl: 'http://berlinjs.org',
  },
  {
    name: 'Kod.io',
    date: '2014-03-01T08:30:00',
    city: 'Linz, Austria',
    talkName: 'i18n and AngularJS',
    summary: 'Meet Pascal and talk about i18n and AngularJS and Kod.io!',
    slidesUrl: 'http://pascalprecht.github.io/slides/angularjs-and-i18n',
    videoUrl: 'https://www.youtube.com/watch?v=C7xqaExvaQ4',
    websiteUrl: 'http://linz.kod.io/',
  },
  {
    name: 'Dutch AngularJS Meetup',
    date: '2013-11-06T19:00:00',
    city: 'Amsterdam, Netherlands',
    talkName: 'i18n with angular-translate',
    summary: 'Pascal presents the angular-translate project, that makes i18n in Angular apps a breeze.',
    slidesUrl: 'http://pascalprecht.github.io/slides/i18n-with-angular-translate',
    videoUrl: 'https://www.youtube.com/watch?v=9CWifOK_Wi8',
    websiteUrl: 'https://plus.google.com/communities/103800317107611206686',
  },
  {
    name: 'HannoverJS',
    date: '2013-09-26T19:00:00',
    city: 'Hanover, Germany',
    talkName: 'Hands on Polymer',
    summary: 'In this talk Pascal shows how Polymer will help to change the way we\'ll build web applications in the future.',
    slidesUrl: 'http://pascalprecht.github.io/slides/hands-on-polymer/#/',
    videoUrl: '',
    websiteUrl: 'http://hannoverjs.de',
  },
  {
    name: 'HannoverJS',
    date: '2013-03-28T19:00:00',
    city: 'Hanover, Germany',
    talkName: 'Mastering AngularJS Directives',
    summary: 'Pascal talks about mastering Angular directives. He mainly shows what directives are, why they are powerful and how to implement them.',
    slidesUrl: 'http://pascalprecht.github.io/slides/mastering-angularjs-directives/#/',
    videoUrl: '',
    websiteUrl: 'http://hannoverjs.de',
  },
  {
    name: 'HannoverJS',
    date: '2013-01-24T19:00:00',
    city: 'Hanover, Germany',
    websiteUrl: 'http://hannoverjs.de',
    videoUrl: '',
    slidesUrl: 'http://pascalprecht.github.io/slides/angularjs-insights/#/',
    talkName: 'AngularJS Insights',
    summary: 'Pascal talks about AngularJS. In this talk he gives a lot of insights on how Angular is actually working and what happens behind the scenes.'
  }
];
