/* jshint unused:false */
var EVENTSDATA = [
  {
    name: 'Voxxed Days Ticino',
    date: '2015-04-18T09:00:00',
    city: 'Ticino, Switzerland',
    websiteUrl: 'https://www.voxxed.com/days-ticino15/',
    videoUrl: '',
    slidesUrl: '',
    talkName: 'Fireside chats about Angular 2.0',
    summary: 'In this talk we want to take a seat, set up a very cozy virtual fireplace and have a relaxed chat about Angular 2.0.'
  },
  {
    name: 'Angular Master Class',
    date: '2015-03-16T09:30:00',
    city: 'Vienna, Austria',
    websiteUrl: 'http://thoughtram.io/angular-master-class.html',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'We are going to run our Angular Master Class in Vienna.'
  },
  {
    name: 'AngularJS Days',
    date: '2015-03-04T09:30:00',
    city: 'Munich, Germany',
    websiteUrl: 'http://angularjs-days.de/2015',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'Say hello in Munich to Christoph and Pascal while they are running two workshops on Angular directives.'
  },
  {
    name: 'NG-NL',
    date: '2015-02-16T09:00:00',
    city: 'Amsterdam, Netherlands',
    websiteUrl: 'http://ng-nl.org',
    videoUrl: '',
    slidesUrl: '',
    talkName: 'The best Angular yet!',
    summary: 'Meet Christoph and Pascal when they talk about the best Angular yet at Amsterdams own AngularJS conference.'
  },
  {
    name: 'Git Master Class',
    date: '2015-01-15T09:30:00',
    city: 'Amsterdam, Netherlands',
    websiteUrl: 'http://thoughtram.io/git-master-class.html',
    videoUrl: '',
    slidesUrl: '',
    talkName: '',
    summary: 'Meet Christoph and Pascal in Amsterdam at the Git Master Class!'
  },
  {
    name: 'ngEurope',
    date: '2014-10-22T08:30:00',
    city: 'Paris, France',
    talkName: '"Don\'t stop thinking about tomorrow!" - AngularJS and Web Components',
    summary: 'Learn how to integrate Web Components with the AngularJS of today in Pascals at ngEurope.',
    slidesUrl: 'http://pascalprecht.github.io/dont-stop-thinking-about-tomorrow',
    videoUrl: 'https://www.youtube.com/watch?v=gSTNTXtQwaY',
    websiteUrl: 'http://ngeurope.org',
  },
  {
    name: 'JsIst',
    date: '2014-09-27T08:30:00',
    city: 'Istanbul, Turkey',
    talkName: 'Disussion Panel',
    summary: 'Join Christoph at the discussion Panel and talk about the web.',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'http://jsist.org',
  },
  {
    name: 'JsIst',
    date: '2014-09-27T08:30:00',
    city: 'Istanbul, Turkey',
    talkName: 'Componentize all the things!',
    summary: 'Hello Istanbul! Pascal talks about Web Components and Polymer.',
    slidesUrl: 'http://pascalprecht.github.io/slides/componentize-all-the-things/#/',
    videoUrl: '',
    websiteUrl: 'http://jsist.org',
  },
  {
    name: 'IstanbulJS',
    date: '2014-09-26T18:30:00',
    city: 'Istanbul, Turkey',
    talkName: 'nickel.rs - Web Application Framework for Rust',
    summary: 'Christoph talks about web application development in Rust',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: 'https://twitter.com/jstanbulorg',
  },
  {
    name: 'Git Training Day',
    date: '2014-09-20T08:30:00',
    city: 'Istanbul, Turkey',
    talkName: '',
    summary: 'Christoph and Pascal are running a free Git Training Day in Istanbul.',
    slidesUrl: '',
    videoUrl: '',
    websiteUrl: '',
  },
  {
    name: 'EnterJS',
    date: '2014-07-01T08:30:00',
    city: 'Cologne, Germany',
    talkName: 'E2E Testing with Protractor',
    summary: 'Pascal is going to talk about E2E testing with the Protractor framework.',
    slidesUrl: 'http://pascalprecht.github.io/slides/e2e-testing-with-protractor',
    videoUrl: '',
    websiteUrl: 'http://enterjs.de/',
  },
  {
    name: 'Codefront.io',
    date: '2014-05-01T08:30:00',
    city: 'Linz, Austria',
    talkName: 'Full Spectrum Testing',
    summary: 'Meet Carmen and Pascal and talk about all things testing!',
    slidesUrl: 'http://pascalprecht.github.io/full-spectrum-testing-slides',
    videoUrl: '',
    websiteUrl: 'http://codefront.io/',
  },
  {
    name: 'JSUnconf',
    date: '2014-04-26T09:00:00',
    city: 'Hamburg, Germany',
    talkName: 'The Secrets of the Git Ninjas',
    summary: 'Christoph on the secrets of Git Ninjas.',
    slidesUrl: 'http://slides.com/cburgdorf/the-secrets-of-the-git-ninjas/#/',
    videoUrl: '',
    websiteUrl: 'http://2014.jsunconf.eu/',
  },
  {
    name: 'Berlin AngularJS Meetup',
    date: '2014-03-12T19:00:00',
    city: 'Berlin, Germany',
    talkName: 'i18n with angular-translate',
    summary: 'Pascal is going to talk about angular-translate and AngularJS. Come and say hi!',
    slidesUrl: 'http://pascalprecht.github.io/slides/i18n-with-angular-translate-2/#/',
    videoUrl: '',
    websiteUrl: 'http://berlinjs.org',
  },
  {
    name: 'Kod.io',
    date: '2014-03-01T08:30:00',
    city: 'Linz, Austria',
    talkName: 'i18n and AngularJS',
    summary: 'Meet Pascal and talk about i18n and AngularJS and Kod.io!',
    slidesUrl: 'http://pascalprecht.github.io/slides/angularjs-and-i18n',
    videoUrl: 'https://www.youtube.com/watch?v=C7xqaExvaQ4',
    websiteUrl: 'http://linz.kod.io/',
  },
  {
    name: 'Dutch AngularJS Meetup',
    date: '2013-11-06T19:00:00',
    city: 'Amsterdam, Netherlands',
    talkName: 'i18n with angular-translate',
    summary: 'Pascal presents the angular-translate project, that makes i18n in Angular apps a breeze.',
    slidesUrl: 'http://pascalprecht.github.io/slides/i18n-with-angular-translate',
    videoUrl: 'https://www.youtube.com/watch?v=9CWifOK_Wi8',
    websiteUrl: 'https://plus.google.com/communities/103800317107611206686',
  },
  {
    name: 'HannoverJS',
    date: '2013-09-26T19:00:00',
    city: 'Hanover, Germany',
    talkName: 'Hands on Polymer',
    summary: 'In this talk Pascal shows how Polymer will help to change the way we\'ll build web applications in the future.',
    slidesUrl: 'http://pascalprecht.github.io/slides/hands-on-polymer/#/',
    videoUrl: '',
    websiteUrl: 'http://hannoverjs.de',
  },
  {
    name: 'HannoverJS',
    date: '2013-03-28T19:00:00',
    city: 'Hanover, Germany',
    talkName: 'Mastering AngularJS Directives',
    summary: 'Pascal talks about mastering Angular directives. He mainly shows what directives are, why they are powerful and how to implement them.',
    slidesUrl: 'http://pascalprecht.github.io/slides/mastering-angularjs-directives/#/',
    videoUrl: '',
    websiteUrl: 'http://hannoverjs.de',
  },
  {
    name: 'HannoverJS',
    date: '2013-01-24T19:00:00',
    city: 'Hanover, Germany',
    websiteUrl: 'http://hannoverjs.de',
    videoUrl: '',
    slidesUrl: 'http://pascalprecht.github.io/slides/angularjs-insights/#/',
    talkName: 'AngularJS Insights',
    summary: 'Pascal talks about AngularJS. In this talk he gives a lot of insights on how Angular is actually working and what happens behind the scenes.'
  }
];
